### ISSUE TITLE
User can get three random dog images

### ISSUE THREAD

**Issue by a-plasencia** [a-plasencia/ajax-project#1]
## ⚙️ Feature

User can get three random dog images

## 💰 Motivation

Dog lovers will want to see different types of dogs

## 📐 Functionality

Create a button that generates three random pictures of dogs each time it is pressed.

## 🖼️ Wireframes

[user can get three random images of dogs mobile] ![Screen Shot 2022-03-03 at 10 47 32 AM](https://user-images.githubusercontent.com/36422433/156632078-5632361e-771d-43be-a365-a7d71992d048.png)

[user can get three random images of dogs desktop] ![Screen Shot 2022-03-03 at 10 48 31 AM](https://user-images.githubusercontent.com/36422433/156632112-e610a0b9-cf38-44f2-8906-ec4648a9b7ce.png)

## ✅ Task List

- [x] Add a `div[data-view="find-dogs"]` to the html.
- [x] Before you click on the Get Dog button, there is a placeholder image in the center.
- [x] Add an unordered list to the `[data-view="find-dogs"]` html.
- [x] Listen for `'click'` events on the Get Dog button, then generate a list of three dog images randomly from the dog-ceo api.  
- [x] Ensure that the three images look good on both desktop and mobile viewports
- [x] Make all three dog images presentable by using css as well as putting a card container around them.
- [x] Add logic where if three pictures already exist, remove those and generate three new pictures.
- [x] Remove all CSS properties that have no effect.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors
