### ISSUE TITLE
User can see the name of the breed of dog under each image

### ISSUE THREAD

**Issue by a-plasencia** [a-plasencia/ajax-project#2]
## ⚙️ Feature

User can see the name of the breed of dog under each image

## 💰 Motivation
Dog lovers will be able to see which breed the dog is, which will let them google it if they would like to learn more.

## 📐 Functionality

Create text that autogenerates when the picture autogenerates with the breed name under the picture.  

## 🖼️ Wireframes

![Screen Shot 2022-03-04 at 10 39 43 AM](https://user-images.githubusercontent.com/36422433/156822836-bfaf79e2-64fd-4b79-8260-262d0775cfce.png)
[user can see the name of the breed of dog under each image mobile view]

![Screen Shot 2022-03-04 at 10 40 12 AM](https://user-images.githubusercontent.com/36422433/156822751-db581ebe-8dd9-48ec-a45b-8f7e982d8804.png)
[user can see the name of the breed of dog under each image desktop view]

## ✅ Task List

- [x] On an example card, put the appropriate breed name and make sure the text matches the figma.
- [x] Get the names of all three dogs on each api call.
- [x] Put the appropriate names under each dog. 
- [x] Ensure that each name and image look good on both desktop and mobile viewports.
- [x] Remove all CSS properties that have no effect.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
