### ISSUE TITLE
User can favorite a dog picture that they like

### ISSUE THREAD

**Issue by a-plasencia** [a-plasencia/ajax-project#3]
## ⚙️ Feature

User can favorite a dog picture that they like.

## 💰 Motivation
Dog lovers will want to be able to pick out which are their favorites.

## 📐 Functionality

To the right of the picture is a star.  This star can be clicked where it will fill in as a favorite.  And can similarly be clicked again to unfavorite a picture.

## 🖼️ Wireframes

[user can favorite a dog picture that they like desktop view]
![Screen Shot 2022-03-04 at 4 05 06 PM](https://user-images.githubusercontent.com/36422433/156858103-4de759c0-3820-464d-b125-2b0ad29640ad.png)

[user can favorite a dog picture that they like mobile view]
![Screen Shot 2022-03-04 at 4 04 49 PM](https://user-images.githubusercontent.com/36422433/156858145-4be5fe9b-9742-4a40-a700-c2ae94e6e2a8.png)

## ✅ Task List

- [x] Go to font awesome and get the star icon and the filled in star icon.
- [x] Get the star icon to appear to the right of the breed name.
- [x] Reformat the `get3Images` function to call a new function called `renderDogs` which will hold all of the DOM tree functionality.
- [x] Have the icon change class name when clicked.  
- [x] Make a data model.
     - [x] Listen for `'click'` events on the Get Dog button and `if` the star icon is filled in.
     - [x] Put the appropriate favorited image and breed name into an object and shift it into data entries data model.
     - [x] Increment the favorites `id`.
- [x] Verify that the favorites are saved to local storage along with the rest of the data model on page reload.  
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
