### ISSUE TITLE
Users can view the list of dogs that they favorited

### ISSUE THREAD

**Issue by a-plasencia** [a-plasencia/ajax-project#4]
## ⚙️ Feature

User can view the list of dogs that they favorited

## 📐 Functionality

Display the user's favorite entries in reverse chronological order so they can see the newest ones first.

## 💰 Motivation
Once a user has recorded some likes, they'll want to see them.

## 🖼️ Wireframes

[user can view their likes mobile]
![feature 4 mobile](https://user-images.githubusercontent.com/36422433/156931483-de42f96b-4242-4fdd-840a-d1307e565f94.PNG)

[user can view their likes desktop]
![feature 4 desktop](https://user-images.githubusercontent.com/36422433/156931507-e9d479f4-387f-4f87-8cd0-62c22aa2d72b.PNG)

## ✅ Task List

- [x] Add a sibling `div[data-view="favorite-dogs"]` to the HTML.
- [x] Add an empty unordered list to the `div[data-view="favorite-dogs"]` element in the HTML.
- [x] If there are no recorded entries in the data model.  Then write a line saying that "No favorites have been recorded" in the favorite-dogs page.
- [x] Add some dummy journal entries to the HTML and ensure that both the desktop and mobile view match the wireframes.
- [x] Use a loop to create a DOM tree for each journal entry in the data model and append it to the page when the `'DOMContentLoaded'` event is fired.
- [x] Add a navigation item to the navbar called Favorites.
- [x] Add an anchor button to the `"find-dogs"` view inside the `"favorite-dogs"` view.
- [x] Ensure that `clicking` the `"Find Dog"` button and `"Favorites"` button in the navbar take you to the respective pages
- [x] Ensure that favoriting more dogs also creates a new DOM tree for it and add is to the page.  
- [x] Ensure that refreshing the page shows the same view as before refreshing.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
