### ISSUE TITLE
User can remove a dog from their favorites list

### ISSUE THREAD

**Issue by a-plasencia** [a-plasencia/ajax-project#5]
## ⚙️ Feature

User can remove a dog from their favorites list

## 📐 Functionality

Allow the user to click the favorite star, and have a modal pop up which will give them the option to remove it.  

## 💰 Motivation
The idea of removing a star from a beautiful dog is hard to fathom, but it's important to give the user the option all the same.

## 🖼️ Wireframes

[user can remove a dog from their favorites list mobile]
![Screen Shot 2022-03-09 at 3 14 56 PM](https://user-images.githubusercontent.com/36422433/157555409-1b14ceaa-1117-44f2-a795-1bd673392897.png)

[user can remove a dog from their favorites list desktop]

![Screen Shot 2022-03-09 at 3 16 08 PM](https://user-images.githubusercontent.com/36422433/157555565-c88e9749-ed1e-4ef9-94ef-31c24ee01a4e.png)

## ✅ Task List

- [x] Make a modal.
- [x] Make a `'click'` listener for the star icons in the unordered list element in the `"favorites-dogs"` view.
- [x] Create two href buttons `Yes` and `No` as well as a message inside of a white box on the modal.  
- [x] Hide the modal if the user clicks `No`.
- [x] Remove the entry from the data model and the entry's DOM tree from the page if the user clicks `Yes`.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
